name: CICD - Build, Push & Deploy Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout קוד
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 3️⃣ Login to ECR
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-east-1 \
        | docker login --username AWS --password-stdin 414444871239.dkr.ecr.us-east-1.amazonaws.com

    # 4️⃣ Build Docker image
    - name: Build Docker image
      run: |
        docker build -t flask-app ./app

    # 5️⃣ Test container locally (optional)
    - name: Run container (test basic)
      run: |
        docker run -d -p 5000:5000 --name test-container flask-app
        sleep 5
        curl -f http://localhost:5000 || exit 1
        docker stop test-container
        docker rm test-container

    # 6️⃣ Tag & Push image to ECR
    - name: Tag and push to ECR
      run: |
        docker tag flask-app:latest 414444871239.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
        docker push 414444871239.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

    # 7️⃣ Deploy via SSM
    - name: Deploy via SSM
      run: |
        aws ssm send-command \
          --targets "Key=tag:Role,Values=flask-server" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Flask App" \
          --parameters commands='[
          "mkdir -p /home/ec2-user/flask-app/secret",
          "echo \"POSTGRES_HOST=${{ secrets.DB_HOST }}\" > /home/ec2-user/flask-app/secret/flask.env",
          "echo \"POSTGRES_PORT=${{ secrets.DB_PORT }}\" >> /home/ec2-user/flask-app/secret/flask.env",
          "echo \"POSTGRES_USER=${{ secrets.DB_USER }}\" >> /home/ec2-user/flask-app/secret/flask.env",
          "echo \"POSTGRES_PASSWORD=${{ secrets.DB_PASS }}\" >> /home/ec2-user/flask-app/secret/flask.env",
          "echo \"POSTGRES_DB=${{ secrets.DB_NAME }}\" >> /home/ec2-user/flask-app/secret/flask.env",
          "chmod 600 /home/ec2-user/flask-app/secret/flask.env",
          "cd /home/ec2-user/flask-app",
          "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 414444871239.dkr.ecr.us-east-1.amazonaws.com",
          "docker pull 414444871239.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest",
          "docker stop flask || true",
          "docker rm flask || true",
          "sudo docker run -d -p 5000:5000 --name flask \
          -v /home/ec2-user/flask-app/secret/flask.env:/app/secret/flask.env \
          --env-file /app/secret/flask.env \
          414444871239.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest"
          ]' \
          --region us-east-1